/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Drawer: typeof import('./components/Drawer.vue')['default']
    Entry: typeof import('./components/Entry.vue')['default']
    Explorer: typeof import('./components/Explorer.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/Settings.vue')['default']
    Themes: typeof import('./components/Themes.vue')['default']
  }
}
